import type { StarterQuestTemplate } from './types';

export const STARTER_QUEST_CATALOG: StarterQuestTemplate[] = [
  // ── Mind: Study Consistently ──────────────────────────────────────────────
  {
    id: 'study_review_notes',
    goalId: 'study_consistently',
    title: "Review yesterday's notes",
    attribute: 'mind',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Briefly scan key insights and diagrams from your previous study session.',
  },
  {
    id: 'study_focus_25',
    goalId: 'study_consistently',
    title: 'Do one focused study block',
    attribute: 'mind',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Immerse in uninterrupted subject study for a full 25-minute cycle.',
  },
  {
    id: 'study_practice_3',
    goalId: 'study_consistently',
    title: 'Solve 3 practice problems',
    attribute: 'mind',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 20,
    intensity: 'balanced',
    description: 'Apply active recall by solving 3 substantive conceptual questions.',
  },
  {
    id: 'study_deep_dive_60',
    goalId: 'study_consistently',
    title: 'Complete a 60-minute deep study session',
    attribute: 'mind',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 60,
    intensity: 'push',
    description: 'Tackle the most demanding theoretical concepts without checking devices.',
  },

  // ── Mind: Improve Focus ───────────────────────────────────────────────────
  {
    id: 'focus_single_task_15',
    goalId: 'improve_focus',
    title: 'Single-task on one priority for 15 minutes',
    attribute: 'mind',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Close extraneous tabs and dedicate pure attention to a single task.',
  },
  {
    id: 'focus_pomodoro_block',
    goalId: 'improve_focus',
    title: 'Work through one distraction-free 25m sprint',
    attribute: 'mind',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Silence notifications and stay present with your main task until the timer rings.',
  },
  {
    id: 'focus_deep_work_45',
    goalId: 'improve_focus',
    title: 'Hold 45 minutes of impenetrable deep work',
    attribute: 'mind',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Enter a state of cognitive flow on a complex challenge with full presence.',
  },

  // ── Mind: Read More ───────────────────────────────────────────────────────
  {
    id: 'read_pages_10',
    goalId: 'read_more',
    title: 'Read 10 pages of a good book',
    attribute: 'mind',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Make steady progress through an enduring physical or digital text.',
  },
  {
    id: 'read_chapter_25',
    goalId: 'read_more',
    title: 'Read one full chapter and annotate a thought',
    attribute: 'mind',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Engage actively with an author’s argument, highlighting notable passages.',
  },
  {
    id: 'read_dense_essay_45',
    goalId: 'read_more',
    title: 'Read a substantive essay or research paper',
    attribute: 'mind',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Dissect a rigorous essay or foundational paper from start to finish.',
  },

  // ── Body: Get Stronger ────────────────────────────────────────────────────
  {
    id: 'body_quick_pushups_10',
    goalId: 'get_stronger',
    title: 'Perform 3 sets of push-ups or squats',
    attribute: 'body',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Awaken muscular tension with bodyweight calisthenics.',
  },
  {
    id: 'body_strength_20',
    goalId: 'get_stronger',
    title: 'Do a 20-minute strength session',
    attribute: 'body',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 20,
    intensity: 'balanced',
    description: 'Complete a focused resistance workout targeting core or upper body strength.',
  },
  {
    id: 'body_heavy_compound_45',
    goalId: 'get_stronger',
    title: 'Complete a 45-minute structured resistance workout',
    attribute: 'body',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Execute progressive compound lifts or high-intensity bodyweight strength sets.',
  },

  // ── Body: Move More ───────────────────────────────────────────────────────
  {
    id: 'body_walk_15',
    goalId: 'move_more',
    title: 'Take a 15-minute walk',
    attribute: 'body',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Step outside or stride without audio distractions to get circulation moving.',
  },
  {
    id: 'body_stretch_mobility_20',
    goalId: 'move_more',
    title: 'Complete a 20-minute mobility and stretch routine',
    attribute: 'body',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 20,
    intensity: 'balanced',
    description: 'Release hip, shoulder, and spinal tension accumulated from seated work.',
  },
  {
    id: 'body_endurance_stride_45',
    goalId: 'move_more',
    title: 'Brisk walk, jog, or cycle for 45 minutes',
    attribute: 'body',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Build steady aerobic resilience with continuous elevated pacing.',
  },

  // ── Body: Sleep Better ────────────────────────────────────────────────────
  {
    id: 'sleep_dim_screens_15',
    goalId: 'sleep_better',
    title: 'Put away all screens 20 minutes before bed',
    attribute: 'body',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Allow melatonin to rise naturally by replacing the glass glow with amber light.',
  },
  {
    id: 'sleep_wind_down_ritual',
    goalId: 'sleep_better',
    title: 'Execute a calming 25-minute evening wind-down',
    attribute: 'body',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Dim lighting, journal your closing thoughts, and prepare clothes for tomorrow.',
  },
  {
    id: 'sleep_protective_routine_40',
    goalId: 'sleep_better',
    title: 'Complete a full nocturnal recovery routine',
    attribute: 'body',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 40,
    intensity: 'push',
    description: 'Stretch, herbal tea, screen blackout, and bedroom temperature prep for deep sleep.',
  },

  // ── Will: Build Discipline ────────────────────────────────────────────────
  {
    id: 'will_plan_tomorrow',
    goalId: 'build_discipline',
    title: "Write tomorrow's three priorities",
    attribute: 'will',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Pre-commit your focus before the morning rush scatters your resolve.',
  },
  {
    id: 'will_hard_task_first_25',
    goalId: 'build_discipline',
    title: 'Tackle the most dreaded task for 25 minutes',
    attribute: 'will',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Do not negotiate with procrastination. Face the hard item head-on.',
  },
  {
    id: 'will_iron_focus_50',
    goalId: 'build_discipline',
    title: 'Execute 50 minutes of uncompromised commitment',
    attribute: 'will',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 50,
    intensity: 'push',
    description: 'Hold the line against urge-surfing, tab-switching, or comfort-seeking.',
  },

  // ── Will: Reduce Screen Time ──────────────────────────────────────────────
  {
    id: 'will_morning_offline_15',
    goalId: 'reduce_screen_time',
    title: 'Spend the first 15 minutes of your morning offline',
    attribute: 'will',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Avoid touching your phone or checking emails right upon waking.',
  },
  {
    id: 'will_screen_boundary',
    goalId: 'reduce_screen_time',
    title: 'Keep one planned screen-free block',
    attribute: 'will',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 30,
    intensity: 'balanced',
    description: 'Leave the phone in another room and immerse in the physical environment.',
  },
  {
    id: 'will_analog_evening_60',
    goalId: 'reduce_screen_time',
    title: 'Enjoy a 60-minute completely analog evening',
    attribute: 'will',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 60,
    intensity: 'push',
    description: 'Read, sketch, converse, or walk without looking at a single digital pixel.',
  },

  // ── Will: Build Confidence ────────────────────────────────────────────────
  {
    id: 'will_speak_up_prompt',
    goalId: 'build_confidence',
    title: 'Voice one clear opinion or question directly',
    attribute: 'will',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Do not withhold your voice out of hesitation or fear of imperfect phrasing.',
  },
  {
    id: 'will_step_into_discomfort_25',
    goalId: 'build_confidence',
    title: 'Confront one overdue conversation or decision',
    attribute: 'will',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Send that difficult message or finalize a choice you have delayed.',
  },
  {
    id: 'will_bold_initiative_45',
    goalId: 'build_confidence',
    title: 'Take bold public initiative on a shared challenge',
    attribute: 'will',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Volunteer to lead, present, or solve an open problem without seeking permission.',
  },

  // ── Will: Organize My Life ────────────────────────────────────────────────
  {
    id: 'will_tidy_workspace_10',
    goalId: 'organize_life',
    title: 'Clear and wipe down your primary workspace',
    attribute: 'will',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Remove cups, papers, and distractions to restore physical order.',
  },
  {
    id: 'will_zero_inbox_25',
    goalId: 'organize_life',
    title: 'Process notifications and desktop clutter for 20m',
    attribute: 'will',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 20,
    intensity: 'balanced',
    description: 'File, respond to, or archive pending pings until your inbox is orderly.',
  },
  {
    id: 'will_system_review_45',
    goalId: 'organize_life',
    title: 'Conduct a thorough weekly calendar and project review',
    attribute: 'will',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Synchronize upcoming commitments, deadlines, and active life queues.',
  },

  // ── Craft: Learn a Skill ──────────────────────────────────────────────────
  {
    id: 'craft_flashcard_drills_15',
    goalId: 'learn_skill',
    title: 'Drill 15 minutes of vocabulary or syntax',
    attribute: 'craft',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 15,
    intensity: 'light',
    description: 'Practice basic patterns in code, grammar, or musical scales.',
  },
  {
    id: 'craft_skill_tutorial_25',
    goalId: 'learn_skill',
    title: 'Work through one practical hands-on tutorial',
    attribute: 'craft',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 25,
    intensity: 'balanced',
    description: 'Follow along with a technical or creative lesson and reproduce the outcome.',
  },
  {
    id: 'craft_deliberate_practice_50',
    goalId: 'learn_skill',
    title: 'Dedicate 50 minutes to deliberate skill practice',
    attribute: 'craft',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 50,
    intensity: 'push',
    description: 'Push against your edge of ability on a difficult song, algorithm, or technique.',
  },

  // ── Craft: Be More Creative ───────────────────────────────────────────────
  {
    id: 'craft_free_write_10',
    goalId: 'be_creative',
    title: 'Write or sketch stream-of-consciousness for 10m',
    attribute: 'craft',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Let words or lines flow onto paper without self-editing or judgment.',
  },
  {
    id: 'craft_make_20',
    goalId: 'be_creative',
    title: 'Make something for 20 focused minutes',
    attribute: 'craft',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 20,
    intensity: 'balanced',
    description: 'Produce a rough draft, sketch, poem, or sound snippet from scratch.',
  },
  {
    id: 'craft_composed_piece_45',
    goalId: 'be_creative',
    title: 'Compose or refine a complete creative vignette',
    attribute: 'craft',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 45,
    intensity: 'push',
    description: 'Develop a creative motif into a structured, expressive short work.',
  },

  // ── Craft: Build a Personal Project ───────────────────────────────────────
  {
    id: 'craft_log_project_note_10',
    goalId: 'build_project',
    title: 'Document architecture or sketch project milestones',
    attribute: 'craft',
    effort: 'quick',
    cadence: 'daily',
    estimatedMinutes: 10,
    intensity: 'light',
    description: 'Clarify the next deliverable before diving into construction.',
  },
  {
    id: 'craft_project_step',
    goalId: 'build_project',
    title: 'Finish one concrete project step',
    attribute: 'craft',
    effort: 'standard',
    cadence: 'daily',
    estimatedMinutes: 30,
    intensity: 'balanced',
    description: 'Implement a specific feature, component, or asset and commit the progress.',
  },
  {
    id: 'craft_project_milestone_60',
    goalId: 'build_project',
    title: 'Ship a working module or user-facing milestone',
    attribute: 'craft',
    effort: 'deep',
    cadence: 'daily',
    estimatedMinutes: 60,
    intensity: 'push',
    description: 'Complete end-to-end wiring of a core feature and verify it works.',
  },
];

export const TEMPLATES_BY_ID = new Map(STARTER_QUEST_CATALOG.map((t) => [t.id, t]));
